export default {
    navigation: {
        timetable: 'Emploi du temps',
        map: 'Carte',
        campusMap: 'Carte du campus',
        food: 'Repas',
        settings: 'Praramètres',
        preferences: 'Préférences',
        flags: 'Fanions',
        flagsSearch: 'Rechercher parmi les fanions',
        allergensSearch: 'Rechercher des allergènes',
        allergens: 'Allergènes',
        details: 'Détails',
        theme: 'Thème',
        profile: 'Profile',
        about: 'À propos',
        advancedSearch: 'Recherche avancée',
        calendar: 'Calendrier',
        examDetails: 'Détails d’examen',
        lecturers: {
            title: 'Professeur·es',
            search: 'Rechercher parmi toutes les professeur·es',
        },
        lecturer: 'Détails de Professeur·e',
        mobility: 'Mobilité',
    },
    cards: {
        titles: {
            timetable: 'Emploi du temps',
            mobility: 'Mobilité',
            calendar: 'Calendrier',
            rooms: 'Salles',
            lecturers: 'Professeur·es',
            news: 'Nouvelles',
            library: 'Bibliothèque',
            events: 'Évènements',
            reimanns: 'Reimanns',
            canisius: 'Canisius Konvikt',
            mensa: 'Cantine',
            food: 'Repas',
        },
        events: {
            by: 'par {{name}}',
        },
        calendar: {
            exam: 'examen {{name}}',
            ends: 'se termine ',
        },
    },
}
